### ISSUE TITLE
ELKの設定

### ISSUE THREAD

**Issue by ichinose9372** [ichinose9372/ft_transcendense_42#55]
監視ツールをセッティング

> Infrastructure Setup with ELK (Elasticsearch, Logstash, Kibana) for Log Management.
> In this major module, the objective is to establish a robust infrastructure for log management and analysis using the ELK stack (Elasticsearch, Logstash, Kibana). Key features and goals include:

 - [x] Deploy Elasticsearch to efficiently store and index log data, making it easily searchable and accessible.
 - [x] Configure Logstash to collect, process, and transform log data from various sources and send it to Elasticsearch.
 - [x] Set up Kibana for visualizing log data, creating dashboards, and generating insights from log events.
 - [x] Define data retention and archiving policies to manage the storage of log data effectively.
 - [x] Implement security measures to protect log data and access to the ELK stack components.
 
>This major module aims to establish a powerful log management and analysis sys- tem using the ELK stack, enabling effective troubleshooting, monitoring, and in- sights into the system’s operation and performance.
This major module aims to establish a powerful log management and analysis sys- tem using the ELK stack, enabling effective troubleshooting, monitoring, and in- sights into the system’s operation and performance.

**Comment by ichinose9372** [comment]
ELK

出力はログファイルにして、それを可視化するという漠然としたイメージからスタートすることにする。

**Comment by yuidvg** [comment]
@ichinose9372 現状どんな感じ?

**Comment by ichinose9372** [comment]
> @ichinose9372 現状どんな感じ?

現状はELKのそれぞれのコンテナをイメージを使って立ち上げるようにしていますが、logstashが立ち上がらない状態です。

エラーのログでは
logstash.confにてどこからのログを受け付けるか、どこに出力するか設定しています。
出力する際にelasticsearchコンテナに出力したいのですが、出力先のコンテナ名を解決できないと言われてlogstashコンテナが終了してしまう状態です。

ポートの設定や名前解決が問題だと思うのと、設定項目が足りてないのかなと思います。

**Comment by ichinose9372** [comment]
@yuidvg 

5/31 
解決できないこと。

dbコンテナとbackendコンテナのログをgelfを使用してlogstashに送る設定にしているが、どうやら送られていない模様。

logstashコンテナに対してudpを使用して直接ログを送り込むテストをすると、処理をされてelasticsearchに送られていることを確認する。

となると、dbコンテナ及びbackendコンテナがログ出力をgelfを使用して送ることができていないことが濃厚。
なんでgelfを使用して送ることができないのかわからない。

**Comment by yuidvg** [comment]
@ichinose9372 logが流れてるかどうか確認する手順が欲しい

**Comment by yuidvg** [comment]
`udp://localhost:12201`
なぜ`localhost`?

**Comment by ichinose9372** [comment]
> @ichinose9372 logが流れてるかどうか確認する手順が欲しい

db、backendコンテナの個別ログはリクエストを送ったり、クエリを投げることで発生するので
dbコンテナの場合
docker exec -it db psql -U user42 -d transcendence_db -c "SELECT 1;"

backendコンテナの場合
curl http://localhost:8000/healthcheck
を使ってみてください

これでdbコンテナとbackendコンテナがログ吐きます。
そのログがlogstashに送られていればいいことになります。

**Comment by ichinose9372** [comment]
> `udp://localhost:12201` なぜ`localhost`?

udp://logstash:12201にするとコンテナ立ち上げの時に名前解決ができなくて立ち上がらないので、localhostにしているって感じです。

**Comment by yuidvg** [comment]
@ichinose9372 なるほど、localhostにするよりはdependencyを設定した方が良さそう

**Comment by ichinose9372** [comment]
> @ichinose9372 なるほど、localhostにするよりはdependencyを設定した方が良さそう

push したやつ確認お願いします。
gelfを使わないでsyslogに設定を変更したらログ流れてそうです。

でもdepenson にしてlogstash のhealthyを確認してからdbを立ち上げることで名前解決できる思ったのですが、それでもできなかったのでlocalhost のままです。

**Comment by yuidvg** [comment]
@ichinose9372 
確認した!いけてるっぽい...?

![Image](https://github.com/ichinose9372/ft_transcendense_42/assets/27997221/1b07ade6-a0ff-4891-86f5-e2c716803df5)

**Comment by ichinose9372** [comment]
> curl http://localhost:8000/healthcheck

そう、なんかできているっぽい

ちょっと設定がわからなくて見れてないw

数も87個のログを記録していることになる？

**Comment by yuidvg** [comment]
監視ツールをセッティング

> Infrastructure Setup with ELK (Elasticsearch, Logstash, Kibana) for Log Management.
> In this major module, the objective is to establish a robust infrastructure for log management and analysis using the ELK stack (Elasticsearch, Logstash, Kibana). Key features and goals include:
> 
> - [ ] Deploy Elasticsearch to efficiently store and index log data, making it easily searchable and accessible.
> - [ ] Configure Logstash to collect, process, and transform log data from various sources and send it to Elasticsearch.
> - [ ] Set up Kibana for visualizing log data, creating dashboards, and generating insights from log events.
> - [ ] Define data retention and archiving policies to manage the storage of log data effectively.
> - [ ] Implement security measures to protect log data and access to the ELK stack components.
> This major module aims to establish a powerful log management and analysis sys- tem using the ELK stack, enabling effective troubleshooting, monitoring, and in- sights into the system’s operation and performance.
This major module aims to establish a powerful log management and analysis sys- tem using the ELK stack, enabling effective troubleshooting, monitoring, and in- sights into the system’s operation and performance.

**Comment by yuidvg** [comment]
@ichinose9372 
あと下記2点のみかな?設定だけぽいけど
- Define data retention and archiving policies to manage the storage of log data effectively.
-  Implement security measures to protect log data and access to the ELK stack components.

**Comment by yuidvg** [comment]
> > curl http://localhost:8000/healthcheck
> 
> そう、なんかできているっぽい
> 
> ちょっと設定がわからなくて見れてないw
> 
> 数も87個のログを記録していることになる？

pongリロードした数だけ増えたからなんかしらの形でlogが伝わっていることは確認できた

**Comment by ichinose9372** [comment]
> @ichinose9372 あと下記2点のみかな?設定だけぽいけど
> 
> * Define data retention and archiving policies to manage the storage of log data effectively.
> * Implement security measures to protect log data and access to the ELK stack components.



``` Define data retention and archiving policies to manage the storage of log data effectively.```
これは保存しているindexのライフサイクルを指定することだと解釈しました。
ELKのそれぞれのコンテナを立ち上げたあとにelasticsearchにcurlでポリシーをリクエストして設定するみたいなので
elasticsearchコンテナにコマンドとして実行しようろしたんですが、depensonとhealthcheckがうまくいかなかったので、ダミーのコンテナを立てて、curl実行だけして終了するコンテナを作成して実行しました。
