### ISSUE TITLE
Make test を frontend-test と backend-testに分ける

### ISSUE THREAD

**Issue by yuidvg** [ichinose9372/ft_transcendense_42#64]

**Comment by ryhara** [comment]
frontテストの現状

make front-build→make front-run(bash立ち上がる)→(コンテナ内のbashで)npm test

**Comment by yuidvg** [comment]
@ryhara これを make frontend-test にonelinerで入れてpushして欲しいです!

**Comment by ryhara** [comment]
@yuidvg make frontend-testだけで実行できるようにしました
このIssueのブランチにpushしてあります
