### ISSUE TITLE
Minor module: Multiple language supports.

### ISSUE THREAD

**Issue by ryhara** [ichinose9372/ft_transcendense_42#86]
> Minor module: Multiple language supports.
In this minor module, the objective is to ensure that your website supports multiple
languages to cater to a diverse user base. Key features and goals include:
◦ Implement support for a minimum of three languages on the website to ac- commodate a broad audience.
 ◦ Provide a language switcher or selector that allows users to easily change the website’s language based on their preferences.
◦ Translate essential website content, such as navigation menus, headings, and key information, into the supported languages.
◦ Ensure that users can navigate and interact with the website seamlessly, re- gardless of the selected language.
◦ Consider using language packs or localization libraries to simplify the transla- tion process and maintain consistency across different languages.
◦ Allow users to set their preferred language as a default choice for subsequent visits to the website.
> 
> This minor module aims to enhance the accessibility and inclusivity of your website by offering content in multiple languages, making it more user-friendly for a diverse international audience.

**Comment by ryhara** [comment]
- [x] 右上や右下に切り替えボタンを用意する
- [x] 最低3言語に対応する
- [x] 翻訳プロセスを簡素化し、異なる言語間の一貫性を維持するために、言語パックまたはローカリゼーション・ライブラリの使用を検討してください。

---
- [ ] ユーザーが希望する言語を、次回以降のウェブサイト訪問時のデフォルト選択として設定できるようにする。

これを満たすのがめんどくさいかも？ユーザー管理をほぼ行っていないので，ユーザーとデフォルト言語を紐づけることが出来ない。

システム全体のデフォルト設定をすることは出来るかも？

jsで値を持っているとリロードすると消えてしまうのでDjangoまたはDBでデフォルト言語の設定を持っていなければならない？

**Comment by yuidvg** [comment]
>  ユーザーが希望する言語を、次回以降のウェブサイト訪問時のデフォルト選択として設定できるようにする。

一旦対応なしで、レビュー項目を見る

**Comment by ryhara** [comment]
ボタンで切り替えだけ出来た
- [ ] 全画面に翻訳用意する
- [ ] 戻る・進むボタンで変わってしまうので変わらないようにした 

https://github.com/ichinose9372/ft_transcendense_42/assets/89718149/47e9917a-5d58-4730-83c2-5dc97677b7bb

**Comment by ryhara** [comment]
以下２つを参考にDjangoで多言語化に対応する
- https://qiita.com/ax-yang/items/0d251f2b91535e909814
- https://zenn.dev/eenymeeny/articles/744b10cefd714c 

追加
- https://docs.djangoproject.com/ja/5.0/topics/i18n/translation/
- https://blog.fantom.co.jp/2020/06/14/django-internationalization-first/

**Comment by ryhara** [comment]
以下をbackendコンテナ起動時にコンテナ内で実行するようにする必要があるかも
```
 python manage.py compilemessages
```
