### ISSUE TITLE
トーナメント終了処理の実装

### ISSUE THREAD

**Issue by welove-t** [ichinose9372/ft_transcendense_42#96]
# やること

## トーナメント終了後
- 試合終了後に表示されるモーダルに優勝者を表示
- 「トーナメント終了ボタン」を設置

## トーナメント終了ボタンを押下後
- DBにappStateのデータを登録する
- トーナメント画面に遷移する

**Comment by ryhara** [comment]
@welove-t 
以下のissueと同じだと思うのでこちらのコメント参考にすると良いかもしれません！

https://github.com/ichinose9372/ft_transcendense_42/issues/94

一旦これはcloseにしたのでこのissueで対応お願いします!!

**Comment by ryhara** [comment]
テスト用に右上に表示しているModal用のボタンや`TODO` と書いてある部分は不要になったら削除お願いします
